version: '3'

services:
  app:
    build:
      args:
        ENVIRONMENT: ${ENVIRONMENT:-production}
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - '8000:8000'

  redis:
    environment:
      - ALLOW_EMPTY_PASSWORD=no
